---
openapi: 3.0.1
info:
  title: Products Management API
  version: v1
consumes:
- application/vnd.product_management.v1+json
produces:
- application/vnd.product_management.v1+json
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
  schemas:
    product:
      type: object
      properties:
        title:
          type: string
        type:
          type: string
        rating:
          type: integer
          format: int32
        price:
          type: string
        created_at:
          type: datetime
        updated_at:
          type: datetime
    new_product:
      type: object
      properties:
        product:
          "$ref": "#/components/schemas/product"
          required:
          - title
          - type
          - price
    new_products_batch:
      type: object
      properties:
        file:
          type: string
          format: base64
    batch_upload:
      type: object
      properties:
        status:
          type: string
        upload_type:
          type: string
    general_error:
      type: object
      required:
      - status
      - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
responses:
  GeneralError:
    description: General Error
    content:
      application/vnd.product_management.v1+json:
        schema:
          "$ref": "#/components/schemas/general_error"
paths:
  "/products/batch":
    post:
      summary: Create products
      security:
      - api_key: []
      operationId: createProducts
      description: Creates a list of products from a provided file
      parameters: []
      responses:
        '201':
          description: A products creation process is created and beying process on
            the background
          content:
            '':
              example:
                id: 51
                status: created
                upload_type: json
            application/vnd.product_management.v1+json:
              schema:
                "$ref": "#/components/schemas/batch_upload"
      requestBody:
        content:
          application/vnd.product_management.v1+json:
            schema:
              "$ref": "#/components/schemas/new_products_batch"
  "/products":
    get:
      summary: List Products
      security:
      - api_key: []
      description: Returns a list of products
      responses:
        '200':
          description: A list of products
          content:
            application/vnd.product_management.v1+json:
              example:
              - id: 1195
                title: Awesome Concrete Plate
                type: Copper
                rating: 1
                price: '5455.0'
                created_at: '2021-04-28T07:25:15.743Z'
              - id: 1196
                title: Intelligent Rubber Computer
                type: Rubber
                rating: 3
                price: '6124.0'
                created_at: '2021-04-28T07:25:15.745Z'
    post:
      summary: Create product
      security:
      - api_key: []
      operationId: createProduct
      description: Creates a product
      parameters: []
      responses:
        '201':
          description: A valid product to be created
          content:
            application/vnd.product_management.v1+json:
              example:
                id: 1197
                title: Ergonomic Wool Chair
                type: Copper
                rating: 1
                price: '9924.0'
                created_at: '2021-04-28T07:25:15.791Z'
              schema:
                "$ref": "#/components/schemas/product"
        '422':
          description: An invalid product
          content:
            application/vnd.product_management.v1+json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/vnd.product_management.v1+json:
            schema:
              "$ref": "#/components/schemas/new_product"
  "/products/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show product
      security:
      - api_key: []
      responses:
        '200':
          description: A product
          content:
            application/vnd.product_management.v1+json:
              example:
                id: 1198
                title: Enormous Cotton Wallet
                type: Marble
                rating: 2
                price: '3259.0'
                created_at: '2021-04-28T07:25:15.832Z'
              schema:
                "$ref": "#/components/schemas/product"
        '404':
          description: Product not found
          content:
            application/vnd.product_management.v1+json:
              example:
                message: ActiveRepository::Base::RecordNotFound
                status: 404
              schema:
                "$ref": "#/components/schemas/general_error"
    patch:
      summary: Update product
      security:
      - api_key: []
      parameters: []
      responses:
        '204':
          description: A product
        '422':
          description: An invalid product
          content:
            application/vnd.product_management.v1+json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
        '404':
          description: Product not found
          content:
            application/vnd.product_management.v1+json:
              schema:
                "$ref": "#/components/schemas/general_error"
      requestBody:
        content:
          application/vnd.product_management.v1+json:
            schema:
              "$ref": "#/components/schemas/new_product"
    put:
      summary: update product
      security:
      - api_key: []
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: An invalid product
          content:
            application/vnd.product_management.v1+json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
        '404':
          description: Product not found
          content:
            application/vnd.product_management.v1+json:
              schema:
                "$ref": "#/components/schemas/general_error"
      requestBody:
        content:
          application/vnd.product_management.v1+json:
            schema:
              "$ref": "#/components/schemas/new_product"
    delete:
      summary: delete product
      security:
      - api_key: []
      responses:
        '204':
          description: successful
        '404':
          description: Product not found
          content:
            application/vnd.product_management.v1+json:
              schema:
                "$ref": "#/components/schemas/general_error"
