---
openapi: 3.0.1
info:
  title: Products Management API
  version: v1
consumes:
- application/json
produces:
- application/json
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
  schemas:
    product:
      type: object
      properties:
        title:
          type: string
        category:
          type: string
        rating:
          type: integer
          format: int32
        price:
          type: string
    new_product:
      type: object
      properties:
        product:
          "$ref": "#/components/schemas/product"
          required:
          - title
          - category
          - price
    general_error:
      type: object
      required:
      - status
      - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
responses:
  GeneralError:
    description: General Error
    content:
      application/json:
        schema:
          "$ref": "#/components/schemas/general_error"
paths:
  "/products":
    get:
      summary: List Products
      security:
      - api_key: []
      description: Returns a list of products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              example:
              - id: 1120
                title: Awesome Marble Knife
                category: Iron
                rating: 5
                price: '2763.0'
                created_at: '2021-04-27T08:18:46.910Z'
                updated_at: '2021-04-27T08:18:46.910Z'
              - id: 1121
                title: Sleek Paper Clock
                category: Wool
                rating: 5
                price: '1994.0'
                created_at: '2021-04-27T08:18:46.912Z'
                updated_at: '2021-04-27T08:18:46.912Z'
    post:
      summary: Create product
      security:
      - api_key: []
      operationId: createProduct
      description: Creates a product
      parameters: []
      responses:
        '201':
          description: A valid product to be created
          content:
            application/json:
              example:
                id: 1122
                title: Heavy Duty Linen Chair
                category: Wool
                rating: 5
                price: '7855.0'
                created_at: '2021-04-27T08:18:46.949Z'
                updated_at: '2021-04-27T08:18:46.949Z'
              schema:
                "$ref": "#/components/schemas/product"
        '422':
          description: An invalid product
          content:
            application/json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_product"
  "/products/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show product
      security:
      - api_key: []
      responses:
        '200':
          description: A product
          content:
            application/json:
              example:
                id: 1123
                title: Gorgeous Iron Clock
                category: Copper
                rating: 4
                price: '6076.0'
                created_at: '2021-04-27T08:18:46.972Z'
                updated_at: '2021-04-27T08:18:46.972Z'
              schema:
                "$ref": "#/components/schemas/product"
        '404':
          description: Product not found
          content:
            application/json:
              example:
                message: ActiveRepository::Base::RecordNotFound
                status: 404
              schema:
                "$ref": "#/components/schemas/general_error"
    patch:
      summary: Update product
      security:
      - api_key: []
      parameters: []
      responses:
        '204':
          description: A product
        '422':
          description: An invalid product
          content:
            application/json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/general_error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_product"
    put:
      summary: update product
      security:
      - api_key: []
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: An invalid product
          content:
            application/json:
              example:
                errors:
                  title:
                  - can't be blank
                  category:
                  - can't be blank
                  price:
                  - can't be blank
                  - is not a number
              schema:
                "$ref": "#/components/schemas/errors_object"
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/general_error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_product"
    delete:
      summary: delete product
      security:
      - api_key: []
      responses:
        '204':
          description: successful
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/general_error"
